# Generated by Django 6.0.3 on 2026-03-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("path", models.CharField(db_index=True, max_length=1024, unique=True)),
                ("depth", models.PositiveIntegerField(default=0)),
                ("body", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, max_length=1024)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="guide.location",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, max_length=1024)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="guide.location",
                    ),
                ),
            ],
            options={
                "ordering": ["section_type"],
                "unique_together": {("location", "slug")},
            },
        ),
    ]
