# Generated by Django 6.0.3 on 2026-03-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="properties",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
