# Generated by Django 5.2.1 on 2026-05-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationsession',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
