# Generated by Django 5.2.1 on 2026-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0002_negotiationsession_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationsession',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiationsession',
            name='proposed_offer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='negotiationsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacting', 'Contacting'), ('negotiating', 'Negotiating'), ('pending_confirmation', 'Offer Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=25),
        ),
    ]
