import random

SCENARIOS = [
    {
        "id": "berlin_friends_3days",
        "context": "You're heading to Berlin for 3 days with your best friend. Which of these would make your list?",
        "destination": "Berlin", "companion": "best friend", "duration": "3 days",
        "options": [
            {"name": "Museum Island", "emoji": "🏛️"},
            {"name": "East Side Gallery", "emoji": "🎨"},
            {"name": "Brandenburg Gate at sunset", "emoji": "🌅"},
            {"name": "A night at Berghain (just try)", "emoji": "🎵"},
            {"name": "Prenzlauer Berg brunch", "emoji": "🥐"},
            {"name": "Tempelhofer Feld picnic", "emoji": "🌿"},
            {"name": "Reichstag dome visit", "emoji": "🔭"},
            {"name": "Street food at Markthalle Neun", "emoji": "🌮"},
            {"name": "Day trip to Potsdam palaces", "emoji": "👑"},
            {"name": "Checkpoint Charlie", "emoji": "🚧"},
        ],
    },
    {
        "id": "tokyo_solo_week",
        "context": "You have a week alone in Tokyo. What goes on the agenda?",
        "destination": "Tokyo", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Senso-ji at dawn (before the crowds)", "emoji": "⛩️"},
            {"name": "TeamLab digital art museum", "emoji": "✨"},
            {"name": "Walk through Yanaka old town", "emoji": "🏘️"},
            {"name": "Ramen at a tiny counter bar", "emoji": "🍜"},
            {"name": "Shibuya crossing at rush hour", "emoji": "🚦"},
            {"name": "Day trip to Nikko", "emoji": "🌲"},
            {"name": "Tsukiji outer market breakfast", "emoji": "🐟"},
            {"name": "Harajuku on a Sunday", "emoji": "🎀"},
            {"name": "Sumo tournament (or practice)", "emoji": "🥊"},
            {"name": "Robot Restaurant (Shinjuku kitsch)", "emoji": "🤖"},
        ],
    },
    {
        "id": "barcelona_partner_5days",
        "context": "Five days in Barcelona with your partner. What makes the cut?",
        "destination": "Barcelona", "companion": "partner", "duration": "5 days",
        "options": [
            {"name": "Sagrada Família (inside)", "emoji": "⛪"},
            {"name": "Park Güell at sunset", "emoji": "🌅"},
            {"name": "La Boqueria early morning", "emoji": "🍊"},
            {"name": "Barceloneta beach morning swim", "emoji": "🏊"},
            {"name": "Vermouth hour in Gràcia", "emoji": "🍸"},
            {"name": "Day trip to Montserrat", "emoji": "⛰️"},
            {"name": "Sant Pau Art Nouveau site", "emoji": "🌺"},
            {"name": "Bunkers del Carmel viewpoint", "emoji": "🔭"},
            {"name": "El Born neighbourhood wander", "emoji": "🪴"},
            {"name": "Dinner at 10pm, like locals do", "emoji": "🍽️"},
        ],
    },
    {
        "id": "newyork_family_weekend",
        "context": "Long weekend in New York with the whole family. What's on the list?",
        "destination": "New York", "companion": "family", "duration": "long weekend",
        "options": [
            {"name": "Central Park — just wander", "emoji": "🌳"},
            {"name": "Top of the Rock or Empire State", "emoji": "🏙️"},
            {"name": "Brooklyn Bridge walk on foot", "emoji": "🌉"},
            {"name": "Chelsea Market lunch", "emoji": "🥪"},
            {"name": "MoMA or the Met (not both)", "emoji": "🖼️"},
            {"name": "Staten Island Ferry (free!)", "emoji": "⛴️"},
            {"name": "Highline walk", "emoji": "🌿"},
            {"name": "Dollar pizza slice tour", "emoji": "🍕"},
            {"name": "One World Observatory", "emoji": "🌆"},
            {"name": "Times Square (briefly, once)", "emoji": "💡"},
        ],
    },
    {
        "id": "paris_partner_3days",
        "context": "Three days in Paris with your partner. Classic or off the beaten path?",
        "destination": "Paris", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "Eiffel Tower after dark (light show)", "emoji": "✨"},
            {"name": "Musée d'Orsay morning", "emoji": "🎨"},
            {"name": "Croissant at a neighbourhood boulangerie", "emoji": "🥐"},
            {"name": "Walk along Canal Saint-Martin", "emoji": "🛶"},
            {"name": "Le Marais afternoon wander", "emoji": "🏚️"},
            {"name": "Montmartre and Sacré-Cœur", "emoji": "⛪"},
            {"name": "Wine and cheese picnic at Champ-de-Mars", "emoji": "🧀"},
            {"name": "Day trip to Versailles", "emoji": "👑"},
            {"name": "Louvre — Mona Lisa or skip to antiquities", "emoji": "🏛️"},
            {"name": "Dinner at a proper bistro, no English menu", "emoji": "🍷"},
        ],
    },
    {
        "id": "amsterdam_friends_weekend",
        "context": "Weekend in Amsterdam with a group of friends. What are you doing?",
        "destination": "Amsterdam", "companion": "friends", "duration": "weekend",
        "options": [
            {"name": "Rijksmuseum morning", "emoji": "🏛️"},
            {"name": "Vondelpark picnic", "emoji": "🌞"},
            {"name": "Canal boat rental (self-drive)", "emoji": "🛶"},
            {"name": "Jordaan brunch and market", "emoji": "🥐"},
            {"name": "Foam photography museum", "emoji": "📷"},
            {"name": "Jenever tasting at a proeflokaal", "emoji": "🥃"},
            {"name": "NDSM shipyard afternoon", "emoji": "🏭"},
            {"name": "Cycling day trip to Haarlem", "emoji": "🚲"},
            {"name": "Late-night stroopwafels at Leidseplein", "emoji": "🍪"},
            {"name": "Hortus Botanicus greenhouse", "emoji": "🌿"},
        ],
    },
    {
        "id": "rome_family_5days",
        "context": "Five days in Rome with the family. Ruins, gelato, and what else?",
        "destination": "Rome", "companion": "family", "duration": "5 days",
        "options": [
            {"name": "Colosseum (pre-booked, early slot)", "emoji": "🏟️"},
            {"name": "Vatican and Sistine Chapel", "emoji": "⛪"},
            {"name": "Trastevere Sunday market", "emoji": "🛍️"},
            {"name": "Gelato comparison tour (5 spots)", "emoji": "🍦"},
            {"name": "Borghese Gallery (must book ahead)", "emoji": "🎨"},
            {"name": "Trevi Fountain at dawn — beat the crowds", "emoji": "⛲"},
            {"name": "Pizza al taglio for lunch, every day", "emoji": "🍕"},
            {"name": "Catacomb visit", "emoji": "🕯️"},
            {"name": "Ostia Antica day trip", "emoji": "🏛️"},
            {"name": "Campo de' Fiori morning market", "emoji": "🌸"},
        ],
    },
    {
        "id": "bali_solo_week",
        "context": "A whole week in Bali, just you. How do you spend it?",
        "destination": "Bali", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Sunrise hike up Mount Batur", "emoji": "🌋"},
            {"name": "Ubud rice terrace walk", "emoji": "🌾"},
            {"name": "Cooking class in Ubud", "emoji": "🍳"},
            {"name": "Temple ceremony at Besakih", "emoji": "🕌"},
            {"name": "Surf lesson in Canggu", "emoji": "🏄"},
            {"name": "Monkey Forest — bold choice", "emoji": "🐒"},
            {"name": "Day trip to Nusa Penida", "emoji": "⛵"},
            {"name": "Morning yoga retreat class", "emoji": "🧘"},
            {"name": "Seminyak sunset beach bar", "emoji": "🌅"},
            {"name": "Traditional healer visit", "emoji": "🌺"},
        ],
    },
    {
        "id": "bangkok_solo_5days",
        "context": "Five solo days in Bangkok. Temples, chaos, and what else?",
        "destination": "Bangkok", "companion": "solo", "duration": "5 days",
        "options": [
            {"name": "Wat Pho at opening time", "emoji": "☸️"},
            {"name": "Grand Palace (long queue, worth it)", "emoji": "🏯"},
            {"name": "Floating market day trip", "emoji": "🛶"},
            {"name": "Street food tour at dusk", "emoji": "🍢"},
            {"name": "Rooftop bar at sunset", "emoji": "🌃"},
            {"name": "Jim Thompson House", "emoji": "🏠"},
            {"name": "Day trip to Ayutthaya ruins", "emoji": "🗿"},
            {"name": "Chatuchak weekend market", "emoji": "🛍️"},
            {"name": "Muay Thai evening fight", "emoji": "🥊"},
            {"name": "Long-tail boat on the Chao Phraya", "emoji": "⛵"},
        ],
    },
    {
        "id": "london_colleagues_2days",
        "context": "Two days in London with work colleagues. Where do you all end up?",
        "destination": "London", "companion": "colleagues", "duration": "2 days",
        "options": [
            {"name": "British Museum (free!)", "emoji": "🏛️"},
            {"name": "Borough Market lunch", "emoji": "🥗"},
            {"name": "Tate Modern afternoon", "emoji": "🎨"},
            {"name": "Walk across Tower Bridge", "emoji": "🌉"},
            {"name": "Pub in Soho after work", "emoji": "🍺"},
            {"name": "Sky Garden (pre-book, also free)", "emoji": "🌿"},
            {"name": "Southbank riverside walk", "emoji": "🚶"},
            {"name": "Churchill War Rooms", "emoji": "🪖"},
            {"name": "Notting Hill afternoon wander", "emoji": "🌸"},
            {"name": "Hyde Park morning walk", "emoji": "🦆"},
        ],
    },
    {
        "id": "sydney_bestfriend_5days",
        "context": "Five days in Sydney with your best friend. Classic or adventure?",
        "destination": "Sydney", "companion": "best friend", "duration": "5 days",
        "options": [
            {"name": "Sydney Opera House tour", "emoji": "🎭"},
            {"name": "Bondi to Coogee coastal walk", "emoji": "🌊"},
            {"name": "Blue Mountains day trip", "emoji": "⛰️"},
            {"name": "Ferry to Manly Beach", "emoji": "⛴️"},
            {"name": "Taronga Zoo with harbour view", "emoji": "🐨"},
            {"name": "Newtown neighbourhood wander", "emoji": "🎸"},
            {"name": "Hunter Valley wine day", "emoji": "🍷"},
            {"name": "Royal Botanic Garden morning", "emoji": "🌺"},
            {"name": "Fish and chips at Watsons Bay", "emoji": "🐟"},
            {"name": "Night market at The Rocks", "emoji": "🌙"},
        ],
    },
    {
        "id": "capetown_solo_week",
        "context": "A week alone in Cape Town. Mountain, ocean, wine — where do you start?",
        "destination": "Cape Town", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Table Mountain cable car (clear day only)", "emoji": "⛰️"},
            {"name": "Robben Island ferry tour", "emoji": "⛴️"},
            {"name": "Boulders Beach penguins", "emoji": "🐧"},
            {"name": "Cape Point and Cape of Good Hope", "emoji": "🌊"},
            {"name": "Wine tasting in Stellenbosch", "emoji": "🍷"},
            {"name": "Bo-Kaap colourful houses walk", "emoji": "🌈"},
            {"name": "Surf lesson at Muizenberg", "emoji": "🏄"},
            {"name": "Sunset at Signal Hill", "emoji": "🌅"},
            {"name": "Sea kayaking from Clifton", "emoji": "🚣"},
            {"name": "Long Street afternoon wander", "emoji": "🚶"},
        ],
    },
    {
        "id": "istanbul_partner_4days",
        "context": "Four days in Istanbul with your partner. East meets West, which parts call to you?",
        "destination": "Istanbul", "companion": "partner", "duration": "4 days",
        "options": [
            {"name": "Hagia Sophia at opening time", "emoji": "🕌"},
            {"name": "Grand Bazaar morning wander", "emoji": "🛍️"},
            {"name": "Topkapi Palace and harem tour", "emoji": "👑"},
            {"name": "Bosphorus sunset cruise", "emoji": "🌅"},
            {"name": "Breakfast spread in Karaköy", "emoji": "🥗"},
            {"name": "Turkish bath (traditional hamam)", "emoji": "♨️"},
            {"name": "Balat neighbourhood walk", "emoji": "🎨"},
            {"name": "Princes' Islands day ferry", "emoji": "⛴️"},
            {"name": "Blue Mosque at dusk", "emoji": "🕌"},
            {"name": "Spice Bazaar and Egyptian Market", "emoji": "🌶️"},
        ],
    },
    {
        "id": "buenosaires_solo_week",
        "context": "A full week in Buenos Aires, solo. Steak, tango, and what else?",
        "destination": "Buenos Aires", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Tango show (dinner + live dance)", "emoji": "💃"},
            {"name": "La Boca and Caminito colours", "emoji": "🎨"},
            {"name": "Recoleta Cemetery (Eva Perón's tomb)", "emoji": "🌹"},
            {"name": "Palermo Soho market on Sunday", "emoji": "🛍️"},
            {"name": "Asado dinner at a parrilla", "emoji": "🥩"},
            {"name": "MALBA modern art museum", "emoji": "🖼️"},
            {"name": "San Telmo Sunday antiques fair", "emoji": "🪙"},
            {"name": "Milonga — dancing with locals", "emoji": "🕺"},
            {"name": "El Ateneo Grand Splendid bookshop", "emoji": "📚"},
            {"name": "Day trip to Tigre delta", "emoji": "🛶"},
        ],
    },
    {
        "id": "mexicocity_friends_4days",
        "context": "Four days in Mexico City with friends. What's on the list?",
        "destination": "Mexico City", "companion": "friends", "duration": "4 days",
        "options": [
            {"name": "Teotihuacán pyramids at sunrise", "emoji": "🌄"},
            {"name": "Frida Kahlo Museum", "emoji": "🌸"},
            {"name": "Churros and hot chocolate at El Moro", "emoji": "☕"},
            {"name": "Lucha libre wrestling match", "emoji": "🤼"},
            {"name": "Mezcal tasting in Condesa", "emoji": "🥃"},
            {"name": "Xochimilco floating gardens", "emoji": "🌺"},
            {"name": "Street tacos at midnight", "emoji": "🌮"},
            {"name": "Palacio de Bellas Artes", "emoji": "🏛️"},
            {"name": "Roma Norte brunch and galleries", "emoji": "🖼️"},
            {"name": "UNAM campus (UNESCO site)", "emoji": "🎓"},
        ],
    },
    {
        "id": "lisbon_bestfriend_4days",
        "context": "Four days in Lisbon with your best friend. Trams, Fado, pastel de nata?",
        "destination": "Lisbon", "companion": "best friend", "duration": "4 days",
        "options": [
            {"name": "Alfama Fado evening", "emoji": "🎵"},
            {"name": "Pastéis de Belém at the original shop", "emoji": "🥮"},
            {"name": "Tram 28 ride (if no queue)", "emoji": "🚋"},
            {"name": "Jerónimos Monastery", "emoji": "⛪"},
            {"name": "LX Factory Sunday market", "emoji": "🛍️"},
            {"name": "Miradouro da Graça for sunset", "emoji": "🌅"},
            {"name": "Sintra day trip — palaces and mist", "emoji": "🏰"},
            {"name": "Time Out Market lunch", "emoji": "🍽️"},
            {"name": "Mouraria neighbourhood walk", "emoji": "🌺"},
            {"name": "Ferry across to Cacilhas for the view", "emoji": "⛴️"},
        ],
    },
    {
        "id": "vienna_partner_3days",
        "context": "Three days in Vienna with your partner. Culture, coffee, and Klimt?",
        "destination": "Vienna", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "Kunsthistorisches Museum", "emoji": "🏛️"},
            {"name": "Wiener Staatsoper (standing tickets are cheap)", "emoji": "🎭"},
            {"name": "Naschmarkt Saturday morning", "emoji": "🧅"},
            {"name": "Belvedere and Klimt's The Kiss", "emoji": "💋"},
            {"name": "Schönbrunn Palace gardens", "emoji": "🌷"},
            {"name": "Coffee at Café Central (old Vienna atmosphere)", "emoji": "☕"},
            {"name": "Prater amusement park and Ferris wheel", "emoji": "🎡"},
            {"name": "Heuriger wine tavern in the hills", "emoji": "🍷"},
            {"name": "Albertina for Monet and Picasso", "emoji": "🎨"},
            {"name": "Vienna Boys' Choir Sunday mass", "emoji": "🎶"},
        ],
    },
    {
        "id": "marrakech_friends_4days",
        "context": "Four days in Marrakech with friends. Souks, spice, and hammams?",
        "destination": "Marrakech", "companion": "friends", "duration": "4 days",
        "options": [
            {"name": "Djemaa el-Fna square at night", "emoji": "🔥"},
            {"name": "Majorelle Garden (Yves Saint Laurent)", "emoji": "🌵"},
            {"name": "Medina souk — get intentionally lost", "emoji": "🧶"},
            {"name": "Hammam and traditional massage", "emoji": "♨️"},
            {"name": "Day trip to Essaouira by coast", "emoji": "🌊"},
            {"name": "Rooftop mint tea with medina view", "emoji": "🫖"},
            {"name": "Saadian Tombs", "emoji": "🕌"},
            {"name": "Cooking class with a local host", "emoji": "🍲"},
            {"name": "Camel ride at the Palmeraie", "emoji": "🐪"},
            {"name": "Bahia Palace", "emoji": "🏛️"},
        ],
    },
    {
        "id": "kyoto_solo_5days",
        "context": "Five solo days in Kyoto. Temples, bamboo, and tea ceremony?",
        "destination": "Kyoto", "companion": "solo", "duration": "5 days",
        "options": [
            {"name": "Fushimi Inari at 6am (before the crowds)", "emoji": "⛩️"},
            {"name": "Arashiyama bamboo grove", "emoji": "🎋"},
            {"name": "Nishiki Market afternoon", "emoji": "🍱"},
            {"name": "Philosopher's Path in cherry blossom season", "emoji": "🌸"},
            {"name": "Nijo Castle and Nightingale floors", "emoji": "🏯"},
            {"name": "Gion district at dusk (geisha sighting?)", "emoji": "🌙"},
            {"name": "Kinkaku-ji (Golden Pavilion)", "emoji": "✨"},
            {"name": "Day trip to Nara deer park", "emoji": "🦌"},
            {"name": "Traditional tea ceremony", "emoji": "🍵"},
            {"name": "Zazen meditation at a temple", "emoji": "🧘"},
        ],
    },
    {
        "id": "prague_friends_weekend",
        "context": "Weekend in Prague with friends. Beer, history, and ruin bars?",
        "destination": "Prague", "companion": "friends", "duration": "weekend",
        "options": [
            {"name": "Charles Bridge at dawn", "emoji": "🌅"},
            {"name": "Old Town Square astronomical clock", "emoji": "⏰"},
            {"name": "Castle District afternoon", "emoji": "🏰"},
            {"name": "Czech beer hall evening (half-litre, please)", "emoji": "🍺"},
            {"name": "Kafka Museum", "emoji": "📚"},
            {"name": "Josefov Jewish Quarter", "emoji": "✡️"},
            {"name": "Day trip to Kutná Hora skull church", "emoji": "💀"},
            {"name": "Vinohrady neighbourhood walk", "emoji": "🌿"},
            {"name": "Black light theatre show", "emoji": "🌟"},
            {"name": "Lokál restaurant for svíčková", "emoji": "🍖"},
        ],
    },
    {
        "id": "seoul_solo_week",
        "context": "Seven solo days in Seoul. K-culture, history, and what else?",
        "destination": "Seoul", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Gyeongbokgung Palace at opening", "emoji": "🏯"},
            {"name": "Insadong tea house and crafts", "emoji": "🫖"},
            {"name": "Night hike up Bukhansan", "emoji": "🌙"},
            {"name": "Gwangjang Market street food", "emoji": "🍢"},
            {"name": "Bukchon Hanok Village morning walk", "emoji": "🏘️"},
            {"name": "DMZ tour to the North Korean border", "emoji": "🚧"},
            {"name": "Noryangjin Fish Market at 4am", "emoji": "🐠"},
            {"name": "Jjimjilbang (spa sauna) overnight stay", "emoji": "♨️"},
            {"name": "Hongdae Saturday night out", "emoji": "🎤"},
            {"name": "K-pop entertainment district walk", "emoji": "💿"},
        ],
    },
    {
        "id": "rio_partner_5days",
        "context": "Five days in Rio with your partner. Beaches, samba, and Christ on the hill?",
        "destination": "Rio de Janeiro", "companion": "partner", "duration": "5 days",
        "options": [
            {"name": "Christ the Redeemer at sunrise", "emoji": "✝️"},
            {"name": "Ipanema beach afternoon", "emoji": "🌊"},
            {"name": "Sugarloaf Mountain cable car", "emoji": "🚡"},
            {"name": "Favela tour (community-guided)", "emoji": "🏘️"},
            {"name": "Samba show in Lapa", "emoji": "💃"},
            {"name": "Botanical Garden morning walk", "emoji": "🌿"},
            {"name": "Ilha Grande day trip", "emoji": "🏝️"},
            {"name": "Bossa nova bar in Ipanema", "emoji": "🎷"},
            {"name": "Pedra da Gávea hike", "emoji": "🧗"},
            {"name": "Açaí breakfast at Leblon", "emoji": "🫐"},
        ],
    },
    {
        "id": "dublin_friends_weekend",
        "context": "Weekend in Dublin with mates. Guinness, music, and a bit of history?",
        "destination": "Dublin", "companion": "friends", "duration": "weekend",
        "options": [
            {"name": "Guinness Storehouse (book ahead)", "emoji": "🍺"},
            {"name": "Temple Bar pub crawl evening", "emoji": "🎸"},
            {"name": "Kilmainham Gaol history tour", "emoji": "🗝️"},
            {"name": "Trinity College and Book of Kells", "emoji": "📖"},
            {"name": "Howth cliffwalk day trip", "emoji": "🌊"},
            {"name": "National Museum of Ireland (free)", "emoji": "🏺"},
            {"name": "Live trad music at O'Donoghue's", "emoji": "🎶"},
            {"name": "DART train to Dún Laoghaire", "emoji": "🚞"},
            {"name": "Full Irish breakfast — the real thing", "emoji": "🍳"},
            {"name": "Phoenix Park morning walk", "emoji": "🦌"},
        ],
    },
    {
        "id": "athens_bestfriend_5days",
        "context": "Five days in Athens with your best friend. Acropolis down to nightcaps?",
        "destination": "Athens", "companion": "best friend", "duration": "5 days",
        "options": [
            {"name": "Acropolis at opening (8am, beat the heat)", "emoji": "🏛️"},
            {"name": "Monastiraki flea market", "emoji": "🛍️"},
            {"name": "Day trip to Hydra or Aegina", "emoji": "⛵"},
            {"name": "Athens street art in Exarcheia", "emoji": "🎨"},
            {"name": "Acropolis Museum", "emoji": "🗿"},
            {"name": "Rooftop bar with Parthenon view at dusk", "emoji": "🌆"},
            {"name": "Athens Central Market (Varvakios)", "emoji": "🐟"},
            {"name": "Day trip to Cape Sounion", "emoji": "🌊"},
            {"name": "Taverna dinner in Thissio", "emoji": "🫒"},
            {"name": "National Archaeological Museum", "emoji": "🏺"},
        ],
    },
    {
        "id": "havana_solo_week",
        "context": "A full week in Havana on your own. Rum, revolution, and rhythm?",
        "destination": "Havana", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Classic car tour of Old Havana", "emoji": "🚗"},
            {"name": "Hemingway's bars (El Floridita, La Bodeguita)", "emoji": "🍹"},
            {"name": "Malecón seafront at sunset", "emoji": "🌅"},
            {"name": "Day trip to Viñales tobacco farms", "emoji": "🌿"},
            {"name": "Fábrica de Arte Cubano (arts space)", "emoji": "🎨"},
            {"name": "Salsa lesson with a local teacher", "emoji": "💃"},
            {"name": "Revolution Square and museum", "emoji": "✊"},
            {"name": "Tropicana cabaret (once in a lifetime)", "emoji": "🌟"},
            {"name": "Colón Cemetery stroll", "emoji": "🌸"},
            {"name": "Stay in a casa particular", "emoji": "🏠"},
        ],
    },
    {
        "id": "copenhagen_partner_3days",
        "context": "Three days in Copenhagen with your partner. Design, food, and hygge?",
        "destination": "Copenhagen", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "Nyhavn canal afternoon walk", "emoji": "🌊"},
            {"name": "Cycling a whole day (this is Copenhagen)", "emoji": "🚲"},
            {"name": "Tivoli Gardens evening", "emoji": "🎡"},
            {"name": "Christiania free-town wander", "emoji": "🌿"},
            {"name": "Design museum and shops", "emoji": "🪑"},
            {"name": "Torvehallerne food market", "emoji": "🥐"},
            {"name": "Louisiana modern art museum day trip", "emoji": "🖼️"},
            {"name": "Meatpacking District dinner", "emoji": "🥩"},
            {"name": "SMK National Gallery (free Sunday)", "emoji": "🎨"},
            {"name": "New Nordic foodie walk in Christianshavn", "emoji": "🌾"},
        ],
    },
    {
        "id": "montreal_friends_4days",
        "context": "Four days in Montreal with friends. French Canada at its best?",
        "destination": "Montreal", "companion": "friends", "duration": "4 days",
        "options": [
            {"name": "Jean-Talon Market morning", "emoji": "🌽"},
            {"name": "Plateau neighbourhood wander", "emoji": "🏘️"},
            {"name": "Poutine tour (Old Montreal)", "emoji": "🍟"},
            {"name": "Comedy club or improv show", "emoji": "😂"},
            {"name": "Mont Royal sunset hike", "emoji": "🌅"},
            {"name": "Mile End bagels (Fairmount vs St-Viateur)", "emoji": "🥯"},
            {"name": "Underground city in winter (RÉSO)", "emoji": "🏙️"},
            {"name": "Biosphère and Jean-Drapeau Park", "emoji": "🌍"},
            {"name": "St. Joseph's Oratory (massive church)", "emoji": "⛪"},
            {"name": "Jazz festival evening (if June)", "emoji": "🎺"},
        ],
    },
    {
        "id": "cairo_family_5days",
        "context": "Five days in Cairo with the whole family. Pyramids, pharaohs, and chaos?",
        "destination": "Cairo", "companion": "family", "duration": "5 days",
        "options": [
            {"name": "Pyramids of Giza and Sphinx at dawn", "emoji": "🔺"},
            {"name": "Egyptian Museum (mummies!)", "emoji": "⚱️"},
            {"name": "Khan el-Khalili bazaar", "emoji": "🛍️"},
            {"name": "Nile felucca boat at sunset", "emoji": "🌅"},
            {"name": "Day trip to Saqqara and Memphis", "emoji": "🏛️"},
            {"name": "Coptic Cairo neighbourhood", "emoji": "⛪"},
            {"name": "Citadel and Mohamed Ali Mosque", "emoji": "🕌"},
            {"name": "Day trip to Alexandria", "emoji": "🌊"},
            {"name": "Sound and light show at Giza", "emoji": "💡"},
            {"name": "Street food: koshari and ful medames", "emoji": "🥣"},
        ],
    },
    {
        "id": "singapore_solo_4days",
        "context": "Four solo days in Singapore. Clean, intense, and delicious?",
        "destination": "Singapore", "companion": "solo", "duration": "4 days",
        "options": [
            {"name": "Gardens by the Bay Supertrees at night", "emoji": "🌳"},
            {"name": "Hawker centre every meal (no exceptions)", "emoji": "🍜"},
            {"name": "Sentosa Island beach afternoon", "emoji": "🏖️"},
            {"name": "Little India and Chinatown on foot", "emoji": "🌺"},
            {"name": "Marina Bay Sands rooftop (non-hotel access)", "emoji": "🏊"},
            {"name": "Night Safari (world's first)", "emoji": "🦁"},
            {"name": "Botanic Gardens UNESCO morning", "emoji": "🌿"},
            {"name": "Haji Lane street art and cafes", "emoji": "🎨"},
            {"name": "Cable car to Sentosa", "emoji": "🚡"},
            {"name": "Day trip to Johor Bahru, Malaysia", "emoji": "🌏"},
        ],
    },
    {
        "id": "budapest_bestfriend_weekend",
        "context": "Weekend in Budapest with your best friend. Baths, ruins, and goulash?",
        "destination": "Budapest", "companion": "best friend", "duration": "weekend",
        "options": [
            {"name": "Széchenyi thermal baths on Saturday morning", "emoji": "♨️"},
            {"name": "Ruin bars (Szimpla Kert) Saturday night", "emoji": "🎉"},
            {"name": "Chain Bridge walk at sunset", "emoji": "🌅"},
            {"name": "Castle Hill and Fisherman's Bastion", "emoji": "🏰"},
            {"name": "Great Market Hall street food", "emoji": "🥘"},
            {"name": "Hungarian Parliament river view", "emoji": "🏛️"},
            {"name": "Jewish Quarter walk and Shoes memorial", "emoji": "✡️"},
            {"name": "Escape room evening", "emoji": "🔐"},
            {"name": "Goulash soup at a terrace restaurant", "emoji": "🍲"},
            {"name": "Day trip to Eger wine caves", "emoji": "🍷"},
        ],
    },
    {
        "id": "sanfrancisco_solo_4days",
        "context": "Four solo days in San Francisco. Fog, hills, and Mission burritos?",
        "destination": "San Francisco", "companion": "solo", "duration": "4 days",
        "options": [
            {"name": "Golden Gate Bridge walk to Marin side", "emoji": "🌉"},
            {"name": "Alcatraz night audio tour", "emoji": "🏝️"},
            {"name": "Mission District murals walk", "emoji": "🎨"},
            {"name": "Fisherman's Wharf clam chowder in a bread bowl", "emoji": "🦪"},
            {"name": "Muir Woods day trip", "emoji": "🌲"},
            {"name": "Castro neighbourhood afternoon", "emoji": "🌈"},
            {"name": "Ferry to Sausalito and cycle back", "emoji": "🚲"},
            {"name": "Dolores Park on a sunny Sunday", "emoji": "☀️"},
            {"name": "Chinatown dim sum morning", "emoji": "🥟"},
            {"name": "Half Moon Bay coastal drive", "emoji": "🌊"},
        ],
    },
    {
        "id": "venice_partner_3days",
        "context": "Three days in Venice with your partner before it sinks further. What's essential?",
        "destination": "Venice", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "Rialto Market at 7am (locals only hour)", "emoji": "🐟"},
            {"name": "Gondola ride at dusk", "emoji": "🛶"},
            {"name": "Doge's Palace and Bridge of Sighs", "emoji": "🏛️"},
            {"name": "Burano island day trip (pastel colours)", "emoji": "🎨"},
            {"name": "Cicchetti bar hop in Cannaregio", "emoji": "🍷"},
            {"name": "Peggy Guggenheim Collection", "emoji": "🖼️"},
            {"name": "St. Mark's Basilica before the crowds", "emoji": "⛪"},
            {"name": "Vaporetto ride along the Grand Canal", "emoji": "⛴️"},
            {"name": "Murano glass-blowing workshop", "emoji": "🫧"},
            {"name": "Torcello — the quiet island", "emoji": "🌿"},
        ],
    },
    {
        "id": "dubrovnik_bestfriend_4days",
        "context": "Four days in Dubrovnik with your best friend. King's Landing or real life?",
        "destination": "Dubrovnik", "companion": "best friend", "duration": "4 days",
        "options": [
            {"name": "City walls walk at sunrise", "emoji": "🌅"},
            {"name": "Game of Thrones filming spots tour", "emoji": "⚔️"},
            {"name": "Cable car up to Mount Srđ", "emoji": "🚡"},
            {"name": "Kayaking around the old town walls", "emoji": "🚣"},
            {"name": "Day trip to Hvar or Korčula", "emoji": "⛵"},
            {"name": "Lokrum island afternoon", "emoji": "🦚"},
            {"name": "Buža cliff bar (hole in the wall)", "emoji": "🌊"},
            {"name": "Old town wander after 9pm", "emoji": "🌙"},
            {"name": "Elaphiti Islands boat trip", "emoji": "🏝️"},
            {"name": "Oysters at Ston (day trip)", "emoji": "🦪"},
        ],
    },
    {
        "id": "hcmc_solo_week",
        "context": "A week alone in Ho Chi Minh City. War history, Mekong, and street food?",
        "destination": "Ho Chi Minh City", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "War Remnants Museum", "emoji": "🕊️"},
            {"name": "Cu Chi Tunnels half-day trip", "emoji": "🕳️"},
            {"name": "Ben Thanh Market morning", "emoji": "🛍️"},
            {"name": "Mekong Delta day trip", "emoji": "🛶"},
            {"name": "Bánh mì breakfast walk", "emoji": "🥖"},
            {"name": "Rooftop cocktails at sunset", "emoji": "🌆"},
            {"name": "Saigon motorbike food tour", "emoji": "🛵"},
            {"name": "Reunification Palace tour", "emoji": "🏛️"},
            {"name": "Day trip to Mui Ne sand dunes", "emoji": "🏜️"},
            {"name": "Old Saigon neighbourhood café hopping", "emoji": "☕"},
        ],
    },
    {
        "id": "edinburgh_friends_3days",
        "context": "Three days in Edinburgh with friends. Whisky, history, and Arthur's Seat?",
        "destination": "Edinburgh", "companion": "friends", "duration": "3 days",
        "options": [
            {"name": "Edinburgh Castle morning", "emoji": "🏰"},
            {"name": "Royal Mile afternoon wander", "emoji": "🚶"},
            {"name": "Arthur's Seat hike (sunrise optional)", "emoji": "⛰️"},
            {"name": "Scotch whisky tasting tour", "emoji": "🥃"},
            {"name": "Calton Hill sunset", "emoji": "🌅"},
            {"name": "Scottish National Museum (free)", "emoji": "🏺"},
            {"name": "Fringe Festival show (if August)", "emoji": "🎭"},
            {"name": "Day trip to Stirling Castle", "emoji": "🏯"},
            {"name": "Greyfriars Kirkyard and Bobby the dog", "emoji": "🐕"},
            {"name": "Fish and chips at Rapido", "emoji": "🐟"},
        ],
    },
    {
        "id": "mumbai_solo_week",
        "context": "Seven solo days in Mumbai. Film, food, and one of the world's biggest cities?",
        "destination": "Mumbai", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Gateway of India at dawn", "emoji": "🌅"},
            {"name": "Dharavi guided walking tour", "emoji": "🏘️"},
            {"name": "Dabbawala lunchbox delivery watch", "emoji": "🍱"},
            {"name": "Elephanta Caves ferry trip", "emoji": "⛴️"},
            {"name": "Dhobi Ghat (open-air laundry) viewing", "emoji": "🧺"},
            {"name": "Bollywood studio tour", "emoji": "🎬"},
            {"name": "Colaba Causeway market browse", "emoji": "🛍️"},
            {"name": "Marine Drive midnight walk", "emoji": "🌙"},
            {"name": "Juhu Beach street food in the evening", "emoji": "🍢"},
            {"name": "Sanjay Gandhi National Park (leopards!)", "emoji": "🐆"},
        ],
    },
    {
        "id": "nairobi_family_5days",
        "context": "Five days in Nairobi with the family. Elephants, giraffes, and more?",
        "destination": "Nairobi", "companion": "family", "duration": "5 days",
        "options": [
            {"name": "Giraffe Centre morning feeding", "emoji": "🦒"},
            {"name": "David Sheldrick Elephant Orphanage", "emoji": "🐘"},
            {"name": "Karen Blixen Museum (Out of Africa)", "emoji": "🏠"},
            {"name": "Nairobi National Park game drive", "emoji": "🦁"},
            {"name": "Bomas of Kenya cultural show", "emoji": "🎭"},
            {"name": "Day trip to Lake Nakuru flamingos", "emoji": "🦩"},
            {"name": "Maasai Market arts and crafts", "emoji": "🎨"},
            {"name": "Hell's Gate National Park cycling", "emoji": "🚲"},
            {"name": "Nairobi National Museum", "emoji": "🏺"},
            {"name": "Carnivore restaurant (game meats)", "emoji": "🥩"},
        ],
    },
    {
        "id": "lima_solo_5days",
        "context": "Five solo days in Lima. Ceviche, cliffs, and pre-Columbian gold?",
        "destination": "Lima", "companion": "solo", "duration": "5 days",
        "options": [
            {"name": "Miraflores clifftop sunset park", "emoji": "🌅"},
            {"name": "Larco Museum (pre-Columbian gold and erotica)", "emoji": "🏺"},
            {"name": "Ceviche lunch at La Mar", "emoji": "🐟"},
            {"name": "Barranco bohemian neighbourhood walk", "emoji": "🎨"},
            {"name": "Huaca Pucllana pyramid in the city", "emoji": "🔺"},
            {"name": "Peruvian cooking class", "emoji": "🍳"},
            {"name": "Day trip to Paracas and Ballestas Islands", "emoji": "🦭"},
            {"name": "Pisco sour at the bar that claims to have invented it", "emoji": "🍹"},
            {"name": "El Callao port district", "emoji": "⚓"},
            {"name": "Larcomar cliff-mall at night", "emoji": "🌆"},
        ],
    },
    {
        "id": "porto_partner_3days",
        "context": "Three days in Porto with your partner. Port wine, bookshops, and azulejos?",
        "destination": "Porto", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "Ribeira waterfront at golden hour", "emoji": "🌅"},
            {"name": "Livraria Lello bookshop (buy your ticket)", "emoji": "📚"},
            {"name": "Wine cellars in Vila Nova de Gaia", "emoji": "🍷"},
            {"name": "Francesinha sandwich at a tasca", "emoji": "🥪"},
            {"name": "Foz do Douro coastal walk", "emoji": "🌊"},
            {"name": "Casa da Música for a performance", "emoji": "🎵"},
            {"name": "Igreja de São Francisco gilded interior", "emoji": "✨"},
            {"name": "Day trip to Douro Valley vineyards", "emoji": "🍇"},
            {"name": "Matosinhos for the best grilled fish", "emoji": "🐟"},
            {"name": "Serralves Museum and gardens", "emoji": "🌿"},
        ],
    },
    {
        "id": "tbilisi_friends_4days",
        "context": "Four days in Tbilisi with friends. Georgia's ancient capital — sulphur baths, wine, and feasting?",
        "destination": "Tbilisi", "companion": "friends", "duration": "4 days",
        "options": [
            {"name": "Old town Kala neighbourhood wander", "emoji": "🏘️"},
            {"name": "Narikala fortress sunset view", "emoji": "🌅"},
            {"name": "Sulphur bath in Abanotubani", "emoji": "♨️"},
            {"name": "Natural Georgian wine tasting (amber wine!)", "emoji": "🍷"},
            {"name": "Day trip to Mtskheta and Jvari", "emoji": "⛪"},
            {"name": "Fabrika creative hub", "emoji": "🎨"},
            {"name": "Bazroba flea market on Sunday", "emoji": "🛍️"},
            {"name": "Traditional Georgian supra (feast)", "emoji": "🍽️"},
            {"name": "Cable car to Narikala", "emoji": "🚡"},
            {"name": "Day trip to Gori and Stalin Museum", "emoji": "🏛️"},
        ],
    },
    {
        "id": "oaxaca_solo_5days",
        "context": "Five solo days in Oaxaca. Mezcal, mole, and Monte Albán?",
        "destination": "Oaxaca", "companion": "solo", "duration": "5 days",
        "options": [
            {"name": "Monte Albán ruins at opening time", "emoji": "🗿"},
            {"name": "Mezcal distillery visit and tasting", "emoji": "🥃"},
            {"name": "Day of the Dead cemetery (if November)", "emoji": "🕯️"},
            {"name": "Mole negro cooking class", "emoji": "🍫"},
            {"name": "Hierve el Agua petrified waterfall", "emoji": "💧"},
            {"name": "Mercado Benito Juárez", "emoji": "🌶️"},
            {"name": "Tlacolula Sunday market", "emoji": "🛍️"},
            {"name": "Santo Domingo Church and garden", "emoji": "⛪"},
            {"name": "Zapotec village day visit", "emoji": "🌾"},
            {"name": "Tejate (ancient chocolate drink)", "emoji": "☕"},
        ],
    },
    {
        "id": "reykjavik_partner_4days",
        "context": "Four days in Reykjavik with your partner. Northern lights, geysers, and hot pools?",
        "destination": "Reykjavik", "companion": "partner", "duration": "4 days",
        "options": [
            {"name": "Northern lights hunt (Nov–Mar)", "emoji": "🌌"},
            {"name": "Blue Lagoon (pre-book — always)", "emoji": "💧"},
            {"name": "Golden Circle: Geysir, Gullfoss, Þingvellir", "emoji": "💦"},
            {"name": "Hallgrímskirkja church tower view", "emoji": "⛪"},
            {"name": "Laugardalslaug pool with locals", "emoji": "♨️"},
            {"name": "Whale watching boat trip", "emoji": "🐋"},
            {"name": "Hot dog at Bæjarins Beztu (the famous cart)", "emoji": "🌭"},
            {"name": "Harpa Concert Hall architecture", "emoji": "🎵"},
            {"name": "Drive to Snæfellsjökull glacier", "emoji": "❄️"},
            {"name": "Midnight sun beach walk (June–July)", "emoji": "🌅"},
        ],
    },
    {
        "id": "chiangmai_solo_week",
        "context": "A full week in Chiang Mai on your own. Temples, elephants, and mountains?",
        "destination": "Chiang Mai", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Doi Suthep temple sunrise hike", "emoji": "⛩️"},
            {"name": "Night Bazaar evening", "emoji": "🌙"},
            {"name": "Elephant sanctuary (ethical, no riding)", "emoji": "🐘"},
            {"name": "Old city moat cycling", "emoji": "🚲"},
            {"name": "Thai massage at a training school", "emoji": "💆"},
            {"name": "Cooking class from market to table", "emoji": "🍳"},
            {"name": "Day trip to Pai (mountain town)", "emoji": "⛰️"},
            {"name": "Yi Peng lantern festival (if November)", "emoji": "🏮"},
            {"name": "Muay Thai evening match", "emoji": "🥊"},
            {"name": "Nimman neighbourhood coffee shop trail", "emoji": "☕"},
        ],
    },
    {
        "id": "tallinn_friends_weekend",
        "context": "Weekend in Tallinn with friends. Medieval old town, design, and a sauna?",
        "destination": "Tallinn", "companion": "friends", "duration": "weekend",
        "options": [
            {"name": "Old Town towers and hill walk", "emoji": "🏰"},
            {"name": "Telliskivi Creative City", "emoji": "🎨"},
            {"name": "Viru Gate and Town Hall Square", "emoji": "⏰"},
            {"name": "Kalamaja wooden house district", "emoji": "🏘️"},
            {"name": "Estonian Open Air Museum", "emoji": "🌾"},
            {"name": "Day trip to Helsinki by ferry", "emoji": "⛴️"},
            {"name": "Kiek in de Kök museum and tunnels", "emoji": "🕵️"},
            {"name": "Vana Tallinn liqueur tasting", "emoji": "🥃"},
            {"name": "KUMU modern art museum", "emoji": "🖼️"},
            {"name": "Sauna evening (the Nordic way)", "emoji": "♨️"},
        ],
    },
    {
        "id": "kotor_partner_3days",
        "context": "Three days in Kotor, Montenegro with your partner. Bay views, cats, and ancient walls?",
        "destination": "Kotor", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "City walls hike to St. John's Fortress", "emoji": "⛰️"},
            {"name": "Perast village and Our Lady of the Rocks island", "emoji": "⛵"},
            {"name": "Old town cat wander (there's a cat museum)", "emoji": "🐱"},
            {"name": "Boat trip to Montenegro's beaches", "emoji": "🏖️"},
            {"name": "Kayak on the Bay of Kotor at dawn", "emoji": "🚣"},
            {"name": "Seafood dinner with bay view", "emoji": "🦞"},
            {"name": "Budva old town evening", "emoji": "🌙"},
            {"name": "Church of St. Tryphon", "emoji": "⛪"},
            {"name": "Njeguši village and prosciutto tasting", "emoji": "🍖"},
            {"name": "Durmitor National Park day trip", "emoji": "🏔️"},
        ],
    },
    {
        "id": "sarajevo_bestfriend_3days",
        "context": "Three days in Sarajevo with your best friend. War, resilience, and incredible food?",
        "destination": "Sarajevo", "companion": "best friend", "duration": "3 days",
        "options": [
            {"name": "Tunnel of Hope war history tour", "emoji": "🕊️"},
            {"name": "Baščaršija old bazaar wander", "emoji": "🛍️"},
            {"name": "Latin Bridge (where WWI started)", "emoji": "🌉"},
            {"name": "Bosnian coffee ceremony at Morica Han", "emoji": "☕"},
            {"name": "Galeria 11/07/95 Srebrenica memorial", "emoji": "🕯️"},
            {"name": "Day trip to Mostar and Stari Most bridge", "emoji": "🌉"},
            {"name": "Yellow Fortress sunset view", "emoji": "🌅"},
            {"name": "Ćevapi at Ćevabdžinica Željo (the best)", "emoji": "🥩"},
            {"name": "War siege sniper alley history walk", "emoji": "🚶"},
            {"name": "Cable car to Trebević mountain", "emoji": "🚡"},
        ],
    },
    {
        "id": "medellin_solo_5days",
        "context": "Five solo days in Medellín. Colombia's transformed city — cables, flowers, and coffee?",
        "destination": "Medellín", "companion": "solo", "duration": "5 days",
        "options": [
            {"name": "Cable car up to Comunas 1 and 2", "emoji": "🚡"},
            {"name": "Parque Arví eco-park above the city", "emoji": "🌿"},
            {"name": "Botero Plaza sculptures (giant bronze)", "emoji": "🗿"},
            {"name": "El Poblado neighbourhood evening", "emoji": "🌃"},
            {"name": "Day trip to Guatapé — climb the rock", "emoji": "🧗"},
            {"name": "Metro system tour (Latin America's first)", "emoji": "🚇"},
            {"name": "Laureles neighbourhood cycling", "emoji": "🚲"},
            {"name": "Flower Festival (if August)", "emoji": "🌸"},
            {"name": "Bandeja paisa local food tour", "emoji": "🍽️"},
            {"name": "Pablo Escobar tour (complex, but fascinating)", "emoji": "🚗"},
        ],
    },
    {
        "id": "queenstown_friends_4days",
        "context": "Four days in Queenstown with friends. Adrenaline capital of the world — what are you doing?",
        "destination": "Queenstown", "companion": "friends", "duration": "4 days",
        "options": [
            {"name": "Bungee jumping at AJ Hackett", "emoji": "🤸"},
            {"name": "Milford Sound day trip", "emoji": "🏔️"},
            {"name": "Gondola and luge run", "emoji": "🎿"},
            {"name": "Skydiving over the Remarkables", "emoji": "🪂"},
            {"name": "Lord of the Rings filming locations", "emoji": "💍"},
            {"name": "Shotover Jet boat ride", "emoji": "💨"},
            {"name": "Arrowtown gold rush ghost town", "emoji": "⛏️"},
            {"name": "Wanaka detour and the lonely tree", "emoji": "🌲"},
            {"name": "Wine tasting in Central Otago", "emoji": "🍷"},
            {"name": "Late night on Queenstown's bar strip", "emoji": "🎉"},
        ],
    },
    {
        "id": "fez_partner_3days",
        "context": "Three days in Fez with your partner. The most labyrinthine medina in the world?",
        "destination": "Fez", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "Medina walk — get intentionally lost", "emoji": "🧭"},
            {"name": "Chouara Tanneries leather viewing", "emoji": "🎨"},
            {"name": "Bou Inania Madrasa", "emoji": "🕌"},
            {"name": "Traditional Fassi cooking class", "emoji": "🍲"},
            {"name": "Rooftop restaurant dinner", "emoji": "🌙"},
            {"name": "Dar Batha Museum", "emoji": "🏺"},
            {"name": "Merenid Tombs at sunset", "emoji": "🌅"},
            {"name": "Day trip to Volubilis Roman ruins", "emoji": "🏛️"},
            {"name": "Souk bargaining for leather goods", "emoji": "🛍️"},
            {"name": "Hammam morning", "emoji": "♨️"},
        ],
    },
    {
        "id": "sansebastian_partner_3days",
        "context": "Three days in San Sebastián with your partner. Best food city in Europe?",
        "destination": "San Sebastián", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "La Concha beach morning walk", "emoji": "🌊"},
            {"name": "Pintxos bar hop in Parte Vieja", "emoji": "🍢"},
            {"name": "Monte Igueldo cable car", "emoji": "🚡"},
            {"name": "Michelin-starred dinner (save up for this)", "emoji": "⭐"},
            {"name": "Basque cider house (sagardotegi) visit", "emoji": "🍎"},
            {"name": "Miramar Palace coastal path walk", "emoji": "🌿"},
            {"name": "Aquarium afternoon", "emoji": "🦈"},
            {"name": "Day trip to Biarritz", "emoji": "🏄"},
            {"name": "Surf watching at Zurriola Beach", "emoji": "🌊"},
            {"name": "Txakoli white wine lunch with ocean view", "emoji": "🍷"},
        ],
    },
    {
        "id": "cartagena_solo_5days",
        "context": "Five solo days in Cartagena, Colombia. Walled city, islands, and street life?",
        "destination": "Cartagena", "companion": "solo", "duration": "5 days",
        "options": [
            {"name": "Walled city sunset walk", "emoji": "🌅"},
            {"name": "Playa Blanca day trip by boat", "emoji": "🏖️"},
            {"name": "Getsemaní street art neighbourhood", "emoji": "🎨"},
            {"name": "Rosario Islands snorkelling", "emoji": "🐠"},
            {"name": "Old city rooftop cocktails", "emoji": "🍹"},
            {"name": "Castillo de San Felipe fortress", "emoji": "🏰"},
            {"name": "Palenque Afro-Colombian village visit", "emoji": "🌺"},
            {"name": "Cholado shaved ice dessert", "emoji": "🧊"},
            {"name": "Mercado de Bazurto morning chaos", "emoji": "🛍️"},
            {"name": "Night out in Getsemaní", "emoji": "🎉"},
        ],
    },
    {
        "id": "hanoi_solo_week",
        "context": "A week alone in Hanoi. Old Quarter, bun cha, and beyond?",
        "destination": "Hanoi", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Hoan Kiem Lake morning tai chi watching", "emoji": "🌅"},
            {"name": "Old Quarter 36-street walk", "emoji": "🚶"},
            {"name": "Hoa Lo Prison (the Hanoi Hilton)", "emoji": "🏛️"},
            {"name": "Ha Long Bay 2-day cruise", "emoji": "⛵"},
            {"name": "Temple of Literature", "emoji": "📚"},
            {"name": "Bun cha lunch (Obama ate here too)", "emoji": "🍜"},
            {"name": "Water puppet theatre performance", "emoji": "🎭"},
            {"name": "Tran Quoc Pagoda at dusk", "emoji": "🕌"},
            {"name": "Night train to Sapa (mountain villages)", "emoji": "🚞"},
            {"name": "Egg coffee at Giang Café", "emoji": "☕"},
        ],
    },
    {
        "id": "thessaloniki_bestfriend_3days",
        "context": "Three days in Thessaloniki with your best friend. Greece's underrated second city?",
        "destination": "Thessaloniki", "companion": "best friend", "duration": "3 days",
        "options": [
            {"name": "Aristotelous Square morning walk", "emoji": "🌅"},
            {"name": "White Tower waterfront", "emoji": "🏛️"},
            {"name": "Ano Poli old neighbourhood", "emoji": "🏘️"},
            {"name": "Modiano Market for cheese and olives", "emoji": "🫒"},
            {"name": "Rotunda and Byzantine churches", "emoji": "⛪"},
            {"name": "Bougatsa pastry breakfast (the real thing)", "emoji": "🥧"},
            {"name": "Thessaloniki Museum of Byzantine Culture", "emoji": "🏺"},
            {"name": "Day trip to Vergina royal tombs", "emoji": "👑"},
            {"name": "Sunset drinks at Ladadika", "emoji": "🌅"},
            {"name": "Seafood dinner at Nea Paralia", "emoji": "🦑"},
        ],
    },
    {
        "id": "lagos_solo_4days",
        "context": "Four solo days in Lagos, Nigeria. Africa's biggest city, biggest energy?",
        "destination": "Lagos", "companion": "solo", "duration": "4 days",
        "options": [
            {"name": "Nike Art Gallery (largest in West Africa)", "emoji": "🎨"},
            {"name": "Lekki Conservation Centre canopy walk", "emoji": "🌿"},
            {"name": "Freedom Park Sunday afternoon", "emoji": "🎵"},
            {"name": "Junkyard Lagos street food night", "emoji": "🍢"},
            {"name": "Balogun Market textile chaos", "emoji": "🧶"},
            {"name": "Bar Beach sunset", "emoji": "🌅"},
            {"name": "Afrobeat live music club night", "emoji": "🎶"},
            {"name": "Banana Island boat trip", "emoji": "⛵"},
            {"name": "Terra Kulture arts centre", "emoji": "🏛️"},
            {"name": "Suya grilled meat at a roadside spot", "emoji": "🥩"},
        ],
    },
    {
        "id": "mexico_oaxaca_day_trip",
        "context": "You have one free day during a Mexico road trip and you're near Oaxaca. How do you fill it?",
        "destination": "Day in Oaxaca", "companion": "road trip crew", "duration": "1 day",
        "options": [
            {"name": "Monte Albán — ancient city on a hilltop", "emoji": "🗿"},
            {"name": "Mezcal tasting at a palenque", "emoji": "🥃"},
            {"name": "Zócalo people-watching and coffee", "emoji": "☕"},
            {"name": "Mole negro cooking class if you can squeeze it", "emoji": "🍫"},
            {"name": "Tlayuda for lunch (the Oaxacan pizza)", "emoji": "🫓"},
            {"name": "Textile workshop in a Zapotec village", "emoji": "🧶"},
            {"name": "Santo Domingo Church gilded interior", "emoji": "✨"},
            {"name": "Alebrijes (painted wooden creatures) workshop", "emoji": "🐉"},
            {"name": "Hierve el Agua petrified waterfalls", "emoji": "💧"},
            {"name": "Mercado 20 de Noviembre for grilled meats", "emoji": "🥩"},
        ],
    },
    {
        "id": "berlin_solo_week",
        "context": "A full week alone in Berlin. History, culture, and some of the world's best nightlife?",
        "destination": "Berlin", "companion": "solo", "duration": "7 days",
        "options": [
            {"name": "Topography of Terror documentation centre", "emoji": "🕊️"},
            {"name": "Jewish Museum Berlin (Daniel Libeskind building)", "emoji": "✡️"},
            {"name": "Neues Museum and the Nefertiti bust", "emoji": "🏺"},
            {"name": "Mauerpark flea market Sunday", "emoji": "🛍️"},
            {"name": "Kreuzberg street food and gallery wander", "emoji": "🌮"},
            {"name": "Day trip to Sachsenhausen", "emoji": "🕯️"},
            {"name": "Kino film at a silent art deco cinema", "emoji": "🎬"},
            {"name": "Clubbing at Watergate or Sisyphos", "emoji": "🎵"},
            {"name": "Berlin Philharmonic (cheap standing tickets)", "emoji": "🎻"},
            {"name": "Tempelhof Airport park cycle", "emoji": "🚲"},
        ],
    },
    {
        "id": "florence_partner_3days",
        "context": "Three days in Florence with your partner. The world's greatest art city?",
        "destination": "Florence", "companion": "partner", "duration": "3 days",
        "options": [
            {"name": "Uffizi Gallery (book months ahead)", "emoji": "🎨"},
            {"name": "David at Accademia (smaller queue)", "emoji": "🗿"},
            {"name": "Ponte Vecchio at golden hour", "emoji": "🌅"},
            {"name": "Oltrarno neighbourhood wander", "emoji": "🏘️"},
            {"name": "Piazzale Michelangelo sunrise", "emoji": "🌄"},
            {"name": "Day trip to Siena or San Gimignano", "emoji": "🏰"},
            {"name": "Mercato Centrale lunch", "emoji": "🥩"},
            {"name": "Aperol spritz at a bar by the Arno", "emoji": "🍊"},
            {"name": "Baptistery gilded doors", "emoji": "🚪"},
            {"name": "Florentine steak (bistecca) dinner", "emoji": "🥩"},
        ],
    },
]


def pick_scenarios(n: int = 5, exclude_ids: list | None = None) -> list:
    """Return n randomly-selected scenarios, avoiding exclude_ids."""
    pool = SCENARIOS if not exclude_ids else [s for s in SCENARIOS if s["id"] not in exclude_ids]
    return random.sample(pool, min(n, len(pool)))
